### ISSUE TITLE
Workshop confusion

### ISSUE THREAD

**Issue by pixie79** [abajwa-hw/security-workshops#19]
The following line in the workshop lead us to change all uppercase components like HDFS & HTTP to lowercase which left kerberos broken on restart. Leaving the file alone worked fine.

Paste contents to a file on both IPA host and on the HDP node, making sure to remove empty lines at the end. If you have any principal names that have upper case chars in them, lower case them (e.g. change ambari-qa-Sandbox to ambari-qa-sandbox and change hdfs-Sandbox to hdfs-sandbox)

**Comment by pixie79** [comment]
https://github.com/abajwa-hw/security-workshops/blob/master/Setup-kerberos-IPA-23.md

**Comment by abajwa-hw** [comment]
Thanks, fixed. Yes this was copied from older version of the guide where we we including the cluster name which was mixed case. Now we are removing cluster name from the principal names
