### ISSUE TITLE
TDE - 256 or 128 bit?

### ISSUE THREAD

**Issue by seanorama** [abajwa-hw/security-workshops#21]
@abajwa-hw - Why 256? Is that the updated recommendation.

Today Olivier mentioned that 128 was what he heard last as best practice

https://github.com/abajwa-hw/security-workshops/blame/master/Setup-TDE-23.md#L73

**Comment by abajwa-hw** [comment]
Could well be...this was take from an example I found

**Comment by seanorama** [comment]
Mixed feedback. General consensus is that 128 is respected and a better choice, but there are some government agencies which require 256. In either case, users should check their CPU for the newer encryption logic which greatly improves encryption performance.
